# Workflow de déploiement Frontend AuraMatch sur Cloud Run
name: 'Deploy Frontend to Cloud Run'

on:
  push:
    branches: ['main']
    paths:
      - '**'
      - '!backend/**'
      - '!.github/workflows/deploy-backend.yml'
  workflow_dispatch:
    inputs:
      backend_url:
        description: 'Backend URL (optional)'
        required: false
        type: string

env:
  PROJECT_ID: 'auramatch-470020'
  REGION: 'europe-west1'
  SERVICE: 'auramatch-frontend'
  BACKEND_SERVICE: 'auramatch-backend'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/343501244023/locations/global/workloadIdentityPools/auramatch-pool/providers/github-oidc'
  REGISTRY: 'europe-west1-docker.pkg.dev'
  REPOSITORY: 'auramatch-frontend'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      
      - name: 'Get Backend URL'
        id: backend
        run: |
          if [[ -n "${{ github.event.inputs.backend_url }}" ]]; then
            BACKEND_URL="${{ github.event.inputs.backend_url }}"
          else
            BACKEND_URL=$(gcloud run services describe ${{ env.BACKEND_SERVICE }} \
              --region=${{ env.REGION }} \
              --format="value(status.url)" 2>/dev/null || echo "")
            
            if [[ -z "$BACKEND_URL" ]]; then
              echo "❌ Backend service not found. Deploy backend first."
              exit 1
            fi
          fi
          
          echo "BACKEND_URL=$BACKEND_URL" >> $GITHUB_ENV
      
      - name: 'Create Artifact Registry repository'
        run: |
          gcloud artifacts repositories describe ${{ env.REPOSITORY }} \
            --location=${{ env.REGION }} || \
          gcloud artifacts repositories create ${{ env.REPOSITORY }} \
            --repository-format=docker \
            --location=${{ env.REGION }} \
            --description="AuraMatch Frontend Docker repository"
      
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          registry: ${{ env.REGISTRY }}
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
      
      - name: 'Prepare Frontend Build'
        run: |
          cat > .env.production << EOF
          VITE_API_BASE_URL=${{ env.BACKEND_URL }}
          VITE_SOCKET_URL=${{ env.BACKEND_URL }}
          VITE_NODE_ENV=production
          EOF
          
          cp .dockerignore.frontend .dockerignore
      
      - name: 'Build and Push Frontend Container'
        run: |
          DOCKER_TAG="${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          
          docker build -f Dockerfile.frontend -t "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"
          
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
      
      - name: 'Deploy Frontend to Cloud Run'
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.DOCKER_TAG }}'
          flags: |
            --allow-unauthenticated
            --port=8080
            --memory=512Mi
            --cpu=1
            --min-instances=0
            --max-instances=5
            --concurrency=80
            --timeout=300
      
      - name: 'Update Backend Environment Variables'
        run: |
          FRONTEND_URL="${{ steps.deploy.outputs.url }}"
          
          gcloud run services update ${{ env.BACKEND_SERVICE }} \
            --region=${{ env.REGION }} \
            --update-env-vars="FRONTEND_URL=${FRONTEND_URL}" \
            --update-env-vars="GOOGLE_CALLBACK_URL=${{ env.BACKEND_URL }}/api/auth/google/callback"
      
      - name: 'Show Deployment Summary'
        run: |
          echo "🎉 Frontend deployed successfully!"
          echo "📍 Frontend URL: ${{ steps.deploy.outputs.url }}"
          echo "🔗 Backend URL: ${{ env.BACKEND_URL }}"
